// errorCodeMapping.js
const ErrorCodesEnum = require('./ErrorCodesEnum'); // adjust the path as needed

const errorCodes = {
  [ErrorCodesEnum.CONTINUE]: 'Continue',
  [ErrorCodesEnum.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [ErrorCodesEnum.PROCESSING]: 'Processing',
  [ErrorCodesEnum.EARLY_HINTS]: 'Early Hints',

  [ErrorCodesEnum.OK]: 'OK',
  [ErrorCodesEnum.CREATED]: 'Created',
  [ErrorCodesEnum.ACCEPTED]: 'Accepted',
  [ErrorCodesEnum.NON_AUTHORITATIVE_INFORMATION]: 'Non-Authoritative Information',
  [ErrorCodesEnum.NO_CONTENT]: 'No Content',
  [ErrorCodesEnum.RESET_CONTENT]: 'Reset Content',
  [ErrorCodesEnum.PARTIAL_CONTENT]: 'Partial Content',
  [ErrorCodesEnum.MULTI_STATUS]: 'Multi-Status',
  [ErrorCodesEnum.ALREADY_REPORTED]: 'Already Reported',
  [ErrorCodesEnum.IM_USED]: 'IM Used',

  [ErrorCodesEnum.MULTIPLE_CHOICES]: 'Multiple Choices',
  [ErrorCodesEnum.MOVED_PERMANENTLY]: 'Moved Permanently',
  [ErrorCodesEnum.FOUND]: 'Found',
  [ErrorCodesEnum.SEE_OTHER]: 'See Other',
  [ErrorCodesEnum.NOT_MODIFIED]: 'Not Modified',
  [ErrorCodesEnum.USE_PROXY]: 'Use Proxy',
  [ErrorCodesEnum.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [ErrorCodesEnum.PERMANENT_REDIRECT]: 'Permanent Redirect',

  [ErrorCodesEnum.BAD_REQUEST]: 'Bad Request',
  [ErrorCodesEnum.UNAUTHORIZED]: 'Unauthorized',
  [ErrorCodesEnum.PAYMENT_REQUIRED]: 'Payment Required',
  [ErrorCodesEnum.FORBIDDEN]: 'Forbidden',
  [ErrorCodesEnum.NOT_FOUND]: 'Not Found',
  [ErrorCodesEnum.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [ErrorCodesEnum.NOT_ACCEPTABLE]: 'Not Acceptable',
  [ErrorCodesEnum.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [ErrorCodesEnum.REQUEST_TIMEOUT]: 'Request Timeout',
  [ErrorCodesEnum.CONFLICT]: 'Conflict',
  [ErrorCodesEnum.GONE]: 'Gone',
  [ErrorCodesEnum.LENGTH_REQUIRED]: 'Length Required',
  [ErrorCodesEnum.PRECONDITION_FAILED]: 'Precondition Failed',
  [ErrorCodesEnum.PAYLOAD_TOO_LARGE]: 'Payload Too Large',
  [ErrorCodesEnum.URI_TOO_LONG]: 'URI Too Long',
  [ErrorCodesEnum.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [ErrorCodesEnum.RANGE_NOT_SATISFIABLE]: 'Range Not Satisfiable',
  [ErrorCodesEnum.EXPECTATION_FAILED]: 'Expectation Failed',
  [ErrorCodesEnum.I_AM_A_TEAPOT]: 'I\'m a teapot',
  [ErrorCodesEnum.MISDIRECTED_REQUEST]: 'Misdirected Request',
  [ErrorCodesEnum.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [ErrorCodesEnum.LOCKED]: 'Locked',
  [ErrorCodesEnum.FAILED_DEPENDENCY]: 'Failed Dependency',
  [ErrorCodesEnum.TOO_EARLY]: 'Too Early',
  [ErrorCodesEnum.UPGRADE_REQUIRED]: 'Upgrade Required',
  [ErrorCodesEnum.PRECONDITION_REQUIRED]: 'Precondition Required',
  [ErrorCodesEnum.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [ErrorCodesEnum.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [ErrorCodesEnum.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',

  [ErrorCodesEnum.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [ErrorCodesEnum.NOT_IMPLEMENTED]: 'Not Implemented',
  [ErrorCodesEnum.BAD_GATEWAY]: 'Bad Gateway',
  [ErrorCodesEnum.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [ErrorCodesEnum.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [ErrorCodesEnum.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [ErrorCodesEnum.VARIANT_ALSO_NEGOTIATES]: 'Variant Also Negotiates',
  [ErrorCodesEnum.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [ErrorCodesEnum.LOOP_DETECTED]: 'Loop Detected',
  [ErrorCodesEnum.NOT_EXTENDED]: 'Not Extended',
  [ErrorCodesEnum.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
  [ErrorCodesEnum.FIELDS_MISSING]: 'Field missing',
};

module.exports = errorCodes;
